version: "3.9"

services:
  # 🟢 API de Clientes
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: client-api
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      # URLs que o Kestrel vai ouvir
      ASPNETCORE_URLS: "http://+:5000;https://+:5001"
      # Variável de conexão com o PostgreSQL
      ConnectionStrings__DefaultConnection: "Host=db_client;Port=5432;Database=clientdb;Username=admin;Password=root"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      db_client:
        condition: service_healthy
    networks:
      - client_network
